Doist/ui-extensions

- packages/ui-extensions-core/package.json
- packages/ui-extensions-core/src/doist-card/inputs.ts
Implements the `regex` property that has been added to the DoistCard spec for 0.6.
The property already exists on adaptive cards, we are now making it available for our own spec. The property itself was already part of the [json schema](https://github.com/Doist/ui-extensions/blob/main/schemas/0.6/doist-card.json#L809-L812).
> chore: Adds regex property to TextInput

- package-lock.json
- packages/ui-extensions-react/package.json
- packages/ui-extensions-react/src/components/AdaptiveCardRenderer.css
Updates the loading component to use our own css variable, rather than a twist-based one.
Nothing to test here.
> chore: Creates our own css variable

- .github/workflows/core-ci.yml
- .github/workflows/react-ci.yml
- package-lock.json
- packages/ui-extensions-react/package.json
This upgrades Reactist to [v13.0.0](https://github.com/Doist/reactist/releases/tag/v13.0.0). 
While the breaking changes shouldn't affect anything here, a major version should be released as it will force consuming apps to install the newer version. Ref: https://github.com/semver/semver/issues/502
> chore: Bump Reactist to v13

- package-lock.json
- packages/ui-extensions-react/package.json
Ref: https://github.com/Doist/reactist/releases/tag/v14.0.0
Neither the `Tabs` nor `Tooltip` components are used here, but the ui-extensions-react package will receive a major bump to v5.0.0
> chore: Bump Reactist to v14

- packages/ui-extensions-react/src/components/AdaptiveCardRenderer.test.tsx
This brings across the clipboard test from Twist as it should really live in here anyway.
> chore: Adds Clipboard tests to AdaptiveCardRenderer tests

- package-lock.json
- packages/ui-extensions-react/package.json
- packages/ui-extensions-react/src/types/types.ts
On our apps, we need to handle an internal-only bridge called `consent.required` and is sent back by the dispatch proxy (on Todoist only right now, but Twist will follow), which will tell the apps to display a consent prompt to allow the extension to be given a token with the specified scopes.
I'm adding this new bridge directly, and only, in the react package as this isn't something that should be in the `ui-extensions-core` package for 3rd party devs to use.
> chore: Adds a new bridge for internal use only

- package-lock.json
- packages/ui-extensions-core/package.json
- packages/ui-extensions-core/src/doist-card/containers.test.ts
- packages/ui-extensions-core/src/doist-card/containers.ts
This allows us to create, for example, a Column in the following fashion
``` typescript
const column = Column.fromWithItems({
items: [TextBlock.from({ text: 'kwijibo' })],
})
```
rather than the more cumbersome
``` typescript
const column = new Column()
column.addItem(TextBlock.from({text: 'hello'}))
column.addItem(TextBlock.from({text: 'world'}))
```
> feat: Adds `fromWithItems()` and `fromWithActions()` helper functions

- package-lock.json
- packages/ui-extensions-react/package.json
- packages/ui-extensions-react/src/types/doist-rendering.ts
Follow on from #30 and adds the `ToggleInputist` class that can then be used by the actual renderers.
> chore: Adds ToggleInputist

- package-lock.json
- packages/ui-extensions-core/package.json
- packages/ui-extensions-core/src/doist-card/actions.ts
- packages/ui-extensions-core/src/doist-card/card-elements.ts
- packages/ui-extensions-core/src/index.ts
- packages/ui-extensions-core/src/types/bridges.ts
- packages/ui-extensions-core/src/types/data-exchange.ts
- packages/ui-extensions-core/src/types/index.ts
- packages/ui-extensions-core/src/types/todoist.ts
- packages/ui-extensions-core/src/types/twist.ts
- packages/ui-extensions-core/src/ui-helpers/button-helpers.test.ts
- packages/ui-extensions-core/src/ui-helpers/button-helpers.ts
- packages/ui-extensions-core/src/ui-helpers/card-helpers.ts
- packages/ui-extensions-core/src/ui-helpers/headers.test.ts
- packages/ui-extensions-core/src/ui-helpers/headers.ts
- packages/ui-extensions-core/src/ui-helpers/index.ts
- packages/ui-extensions-core/src/ui-helpers/ui-constants.ts
- packages/ui-extensions-react/package.json
- packages/ui-extensions-react/src/actions/submitAction.ts
- packages/ui-extensions-react/src/components/AdaptiveCardRenderer.css
- packages/ui-extensions-react/src/components/AdaptiveCardRenderer.tsx
- packages/ui-extensions-react/src/hooks/useAdaptiveCardsConnection.test.ts
- packages/ui-extensions-react/src/hooks/useAdaptiveCardsConnection.ts
- packages/ui-extensions-react/src/stories/StorybookConnectedCard.tsx
- packages/ui-extensions-react/src/types/types.ts
This release does a few things, namely:
- Adds `loadingText` property to `SubmitAction`. This will allow extension developers to display some text while the new card is being fetch. Demo: https://share.getcloudapp.com/Kou1bwzX
- Adds `fromWithItems()` to DoistCard, this API is the same as what we have on Container-based objects.
- Improves the types for DoistCardBridge. I have now separated them all into their own type and create a discriminated union type, this will stop people from including `text` when sending a bridge notification, for example.
- Added `request.sync` Bridge. This is for Todoist and will trigger a sync when used. See discussion: https://twist.com/a/1585/ch/190200/t/3851022/
- Added `additionalUserContext` to the Todoist context, this will allow us to let extension …
> feat: UI Extension changes

- package-lock.json
- packages/ui-extensions-core/package.json
- packages/ui-extensions-core/src/types/data-exchange.ts
This allows us to do something like the following and have it correctly typed: 
```typescript
type Thing = {
projectId: string
}
function something(request: DoistCardRequest<{ data: Thing}>) {
const projectId = request.action.data?.projectId
}
```
> feat: Adds a data generic type for DoistCardRequest.

- package-lock.json
- packages/ui-extensions-core/package.json
- packages/ui-extensions-core/src/doist-card/card-elements.ts
Matches the rest of the items that have internal items.
> feat: Adds `fromWithInlines` for RichTextBlock

- package-lock.json
- packages/ui-extensions-core/package.json
- packages/ui-extensions-core/src/types/data-exchange.ts
In line with Todoist API sending ids back as strings, the context for a user in UI extensions should also support being sent as a string.
This needs to be a `number | string` type because this package is still used in Twist where those IDs are still numbers.
> chore: Updates user context id to support string

- package-lock.json
- packages/ui-extensions-react/package.json
- packages/ui-extensions-react/src/renderers/action-renderers.tsx
Action rendering was still using `DeprecatedButton` from Reactist, but we should really be moving to the main `Button` component. This PR addresses that.
> chore: Removes DeprecatedButton usage.

- package-lock.json
- packages/ui-extensions-core/package.json
- packages/ui-extensions-core/src/types/data-exchange.ts
- packages/ui-extensions-core/src/types/doist.ts
- packages/ui-extensions-core/src/types/index.ts
- packages/ui-extensions-core/src/types/todoist.ts
- packages/ui-extensions-core/src/types/twist.ts
A previous change to the `user.id` field in the `DoistCardContextUser` resulted in potential confusion on types usage. 
This PR splits that user into a Twist/Todoist variant, with `DoistCardContextUser` accepting either. This means if you have already been using DoistCardContextUser prior to the `number | string` change, you can just choose to use `TwistContextUser` as the type to avoid any type issues.
> chore: Splits the User context to be Todoist/Twist specific

- package-lock.json
- packages/ui-extensions-react/.storybook/main.js
- packages/ui-extensions-react/package.json
In theory, none of Reactist's breaking changes from v15 to v21 affect the ui-extensions-react components. @scottlovegrove , can you double check?
Bumping the version to 10.0.0 (major) as a peer dependency version is changed, which forces consumers of this library to update it too.
> chore: update Reactist to v21 and bump version to 10.0.0

- package-lock.json
- packages/ui-extensions-react/package.json
After today's Reactist update in this repo (https://github.com/Doist/ui-extensions/pull/55), a new Reactist version was released (v22.0.0). The breaking changes don't affect this library.
Bumping the version to 11.0.0 (major) as a peer dependency version is changed, which forces consumers of this library to update it too.
> chore: update Reactist to v22

- package-lock.json
- package.json
Does an audit fix.
Also noticed that unlike our other extension related repos, the audit script wasn't set to just check production dependencies. Have corrected. that.
> chore: Does an audit fix and adjusts audit script

- package-lock.json
- packages/ui-extensions-react/package.json
This is an attempt to release a beta version of `@doist/ui-extensions-react`, one that uses the latest beta version of Reactist.
> chore(deps): Upgrade Reactist to v24.0.0-beta

- package-lock.json
- packages/ui-extensions-react/package.json
- packages/ui-extensions-react/src/components/adaptive-card/AdaptiveCardRenderer.tsx
Performs a check on the url to ensure that it's a valid http/https url, this will help prevent XSS
Fixes https://github.com/Doist/Issues/issues/13973
> fix: Ensure url is valid before opening to prevent XSS

- package-lock.json
- packages/ui-extensions-react/package.json
Now that Reactist is back to having all the new changes in a stable non-beta release (v25.0.0), this pull request brings that Reactist version to the ui-extensions, and brings this repo's recent changes in `next` back to `main`.
This pull request will be released as a new version v13.0.0 of the ui extensions react package.
> new stable release v13.0.0

- package-lock.json
- packages/ui-extensions-react/package.json
This PR bumps both the dev and peer dependency of `@doist/reactist` to `v26.0.0`.
> chore: Bump `@doist/reactist` to `v26.0.0`

- packages/ui-extensions-react/package.json
Forgot that I was supposed to have done this in https://github.com/Doist/ui-extensions/pull/73.
> chore: Bump `@doist/ui-extensions-react` to v14

- package-lock.json
- packages/ui-extensions-react/package.json
This PR bumps both the dev and peer dependency of `@doist/reactist` to `v28.0.0`.
> chore(deps): Bump Reactist to v28

- packages/ui-extensions-react/package.json
To release https://github.com/Doist/ui-extensions/pull/114.
> chore: Bump `@doist/ui-extensions-react` to v16
